# 2023 Day 3: Gear Ratios

## Part 1


You and the Elf eventually reach a gondola lift station; he says the gondola lift will take you up to the water source, but this is as far as he can bring you. You go inside.

It doesn't take long to find the gondolas, but there seems to be a problem: they're not moving.

"Aaah!"

You turn around to see a slightly-greasy Elf with a wrench and a look of surprise. "Sorry, I wasn't expecting anyone! The gondola lift isn't working right now; it'll still be a while before I can fix it." You offer to help.

The engineer explains that an engine part seems to be missing from the engine, but nobody can figure out which one. If you can add up all the part numbers in the engine schematic, it should be easy to work out which part is missing.

The engine schematic (your puzzle input) consists of a visual representation of the engine. There are lots of numbers and symbols you don't really understand, but apparently any number adjacent to a symbol, even diagonally, is a "part number" and should be included in your sum. (Periods (.) do not count as a symbol.)

Here is an example engine schematic:

```
467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
```

In this schematic, two numbers are not part numbers because they are not adjacent to a symbol: 114 (top right) and 58 (middle right). Every other number is adjacent to a symbol and so is a part number; their sum is 4361.

Of course, the actual engine schematic is much larger. What is the sum of all of the part numbers in the engine schematic?

In [1]:
# Setting the sample input
sample_input = '''467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..'''.split('\n')

sample_input

['467..114..',
 '...*......',
 '..35..633.',
 '......#...',
 '617*......',
 '.....+.58.',
 '..592.....',
 '......755.',
 '...$.*....',
 '.664.598..']

In [2]:
# Loading the full input
with open('input.txt', 'r') as f:
    engine_schematic = f.read().splitlines()

In [3]:
# Instantiating a set to hold all of the special characters
special_chars = set()

# Extracting all the special characters
for row in engine_schematic:
    
    # Iterating over all the characters in the row
    for char in list(row):
        
        # Checking if the character is a digit or a period
        if not (char == '.' or char.isdigit()):
            special_chars.add(char)
            
print(special_chars)

{'=', '*', '+', '-', '/', '@', '#', '$', '%', '&'}


In [4]:
# Setting the sample input as the engine schematic for testing purposes
engine_schematic = sample_input

In [5]:
def check_adjacency(row_number, starting_pos, ending_pos):
    '''
    Checks if the number is adjacent to any special characters
    
    Inputs:
        - row_number (int): The current row we are working in
        - starting_pos (int): The starting index position of the number we are currently working with
        - ending_pos (int): The ending index position of the number we are currently working with
        
    Returns:
        - (boolean): A boolean indicator where "True" means it is adjacent and "False" means it is not
    '''
    
    # Referencing the full engine schematic and special characters as global variables
    global engine_schematic
    global special_chars
    
    # Iterating over all the characters within the starting and ending positions
    for current_pos in range(starting_pos, ending_pos + 1):
        
        # Wrapping everything in a try-except block to catch out-of-bounds errors
        try:
        
            # Checking the top left adjacency
            if engine_schematic[row_number - 1][current_pos - 1] in special_chars:
                return True

            # Checking top adjacency
            if engine_schematic[row_number - 1][current_pos] in special_chars:
                return True

            # Checking top right adjacency
            if engine_schematic[row_number - 1][current_pos + 1] in special_chars:
                return True

            # Checking left adjacency
            if engine_schematic[row_number][current_pos - 1] in special_chars:
                return True

            # Checking right adjacency
            if engine_schematic[row_number][current_pos + 1] in special_chars:
                return True

            # Checking bottom left adjacency
            if engine_schematic[row_number + 1][current_pos - 1] in special_chars:
                return True

            # Checking bottom adjacency
            if engine_schematic[row_number + 1][current_pos] in special_chars:
                return True

            # Checking bottom right adjacency
            if engine_schematic[row_number + 1][current_pos + 1] in special_chars:
                return True
        
        # Continuing past any errors related to out-of-bounds concerns
        except IndexError:
            continue
    
    # Returning False if no adjacent characters found 
    return False

In [6]:
# Instantiating a value to represent the final sum
final_sum = 0

# Instantiating a value to represent the row number
row_number = 0

# Iterating over all the lines in the engine schematic
while row_number < len(engine_schematic):
    
    # Getting the current row
    current_row = engine_schematic[row_number]

    # Converting the string to a list of values
    row_list = list(current_row)

    # Instantiating a value to represent the index position
    i = 0

    # Instantiating values to represent starting and ending positions of numbers
    starting_pos = -1
    ending_pos = -1

    # Iterating over each character in the row
    while i < len(row_list):

        # Getting the current character in the row
        current_char = row_list[i]

        # Checking if the current character is a digit and is the new starting position
        if current_char.isdigit() and starting_pos == -1:

            # Setting the current position as the starting position
            starting_pos = i
            
            # Checking if this is a single digit
            if not engine_schematic[row_number][starting_pos + 1].isdigit() or i == len(row_list) - 1:
                
                # Checking if the single number is adjacent to any special characters
                is_adjacent = check_adjacency(row_number, starting_pos, starting_pos + 1)
                
                # Incrementing the final sum for any numbers adjacent to a special character
                if is_adjacent:
                    final_sum += int(engine_schematic[row_number][starting_pos])
                    
                # Resetting the starting position
                starting_pos = -1

        # Checking if this is a digit at the end of a row
        elif current_char.isdigit() and i == len(row_list) - 1:

            # Setting the current position as the ending position
            ending_pos = i
            
            # Checking if this number is adjacent to any special characters
            is_adjacent = check_adjacency(row_number, starting_pos, ending_pos)
            
            # Incrementing the final sum for any numbers adjacent to a special character
            if is_adjacent:
                final_sum += int(engine_schematic[row_number][starting_pos:ending_pos + 1])
            
            # Resetting the starting and ending positions
            starting_pos = -1
            ending_pos = -1

        # Checking if this is a digit that isn't in the starting position but also not at the end of the row
        elif current_char.isdigit() and starting_pos != -1 and (engine_schematic[row_number][i + 1] == '.' or engine_schematic[row_number][i + 1] in special_chars):
            
            # Setting the current position as the ending position
            ending_pos = i
            
            # Checking if this number is adjacent to any special characters
            is_adjacent = check_adjacency(row_number, starting_pos, ending_pos)
            
            # Incrementing the final sum for any numbers adjacent to a special character
            if is_adjacent:
                final_sum += int(engine_schematic[row_number][starting_pos:ending_pos + 1])
            
            # Resetting the starting and ending positions
            starting_pos = -1
            ending_pos = -1

        # Incrementing the index position
        i += 1
        
    # Moving to the next row
    row_number += 1
    
# Printing the final sum
print(f'Final sum: {final_sum}')

Final sum: 556367


## Part 2

The engineer finds the missing part and installs it in the engine! As the engine springs to life, you jump in the closest gondola, finally ready to ascend to the water source.

You don't seem to be going very fast, though. Maybe something is still wrong? Fortunately, the gondola has a phone labeled "help", so you pick it up and the engineer answers.

Before you can explain the situation, she suggests that you look out the window. There stands the engineer, holding a phone in one hand and waving with the other. You're going so slowly that you haven't even left the station. You exit the gondola.

The missing part wasn't the only issue - one of the gears in the engine is wrong. A gear is any * symbol that is adjacent to exactly two part numbers. Its gear ratio is the result of multiplying those two numbers together.

This time, you need to find the gear ratio of every gear and add them all up so that the engineer can figure out which gear needs to be replaced.

Consider the same engine schematic again:
```
467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
```
In this schematic, there are two gears. The first is in the top left; it has part numbers 467 and 35, so its gear ratio is 16345. The second gear is in the lower right; its gear ratio is 451490. (The * adjacent to 617 is not a gear because it is only adjacent to one part number.) Adding up all of the gear ratios produces 467835.

What is the sum of all of the gear ratios in your engine schematic?

In [ ]:
def find_gears(row_number, starting_pos, ending_pos):
    '''
    Checks if the number is adjacent to any gears
    
    Inputs:
        - row_number (int): The current row we are working in
        - starting_pos (int): The starting index position of the number we are currently working with
        - ending_pos (int): The ending index position of the number we are currently working with
        
    Returns:
        - gear_position (tuple): The position of the current gear
    '''
    
    # Referencing the full engine schematic and special characters as global variables
    global engine_schematic
    global special_chars
    
    # Iterating over all the characters within the starting and ending positions
    for current_pos in range(starting_pos, ending_pos + 1):
        
        # Wrapping everything in a try-except block to catch out-of-bounds errors
        try:
        
            # Checking the top left adjacency
            if engine_schematic[row_number - 1][current_pos - 1] == '*':
                return (row_number - 1, current_pos - 1)

            # Checking top adjacency
            if engine_schematic[row_number - 1][current_pos] == '*':
                return (row_number - 1, current_pos)

            # Checking top right adjacency
            if engine_schematic[row_number - 1][current_pos + 1] == '*':
                return (row_number - 1, current_pos + 1)

            # Checking left adjacency
            if engine_schematic[row_number][current_pos - 1] == '*':
                return (row_number, current_pos - 1)

            # Checking right adjacency
            if engine_schematic[row_number][current_pos + 1] == '*':
                return (row_number, current_pos + 1)

            # Checking bottom left adjacency
            if engine_schematic[row_number + 1][current_pos - 1] == '*':
                return (row_number + 1, current_pos - 1)

            # Checking bottom adjacency
            if engine_schematic[row_number + 1][current_pos] == '*':
                return (row_number + 1, current_pos)

            # Checking bottom right adjacency
            if engine_schematic[row_number + 1][current_pos + 1] == '*':
                return (row_number + 1, current_pos + 1)
        
        # Continuing past any errors related to out-of-bounds concerns
        except IndexError:
            continue

In [ ]:
# Instantiating a value to represent the final sum
final_sum = 0

# Instantiating a value to represent the row number
row_number = 0

# Iterating over all the lines in the engine schematic
while row_number < len(engine_schematic):
    
    # Getting the current row
    current_row = engine_schematic[row_number]

    # Converting the string to a list of values
    row_list = list(current_row)

    # Instantiating a value to represent the index position
    i = 0

    # Instantiating values to represent starting and ending positions of numbers
    starting_pos = -1
    ending_pos = -1

    # Iterating over each character in the row
    while i < len(row_list):

        # Getting the current character in the row
        current_char = row_list[i]

        # Checking if the current character is a digit and is the new starting position
        if current_char.isdigit() and starting_pos == -1:

            # Setting the current position as the starting position
            starting_pos = i
            
            # Checking if this is a single digit
            if not engine_schematic[row_number][starting_pos + 1].isdigit() or i == len(row_list) - 1:
                    
                # Resetting the starting position
                starting_pos = -1

        # Checking if this is a digit at the end of a row
        elif current_char.isdigit() and i == len(row_list) - 1:

            # Setting the current position as the ending position
            ending_pos = i
            
            # Resetting the starting and ending positions
            starting_pos = -1
            ending_pos = -1

        # Checking if this is a digit that isn't in the starting position but also not at the end of the row
        elif current_char.isdigit() and starting_pos != -1 and (engine_schematic[row_number][i + 1] == '.' or engine_schematic[row_number][i + 1] in special_chars):
            
            # Setting the current position as the ending position
            ending_pos = i
            
            # Resetting the starting and ending positions
            starting_pos = -1
            ending_pos = -1

        # Incrementing the index position
        i += 1
        
    # Moving to the next row
    row_number += 1
    
# Printing the final sum
print(f'Final sum: {final_sum}')